export default [
  //
  // MAPS
  //
  {
    type: "category",
    title: "Maps",
    category: "maps",
    subTitle: "Add custom maps to web and mobile apps.",
  },
  {
    type: "tile",
    title: "Mapbox GL JS",
    category: "maps",
    subTitle: "Impressive WebGL Map Rendering",
    link: "https://docs.mapbox.com/mapbox-gl-js/guides/",
    iconClass: "fa-brands fa-square-js",
  },
  {
    type: "tile",
    title: "Mapbox Tiling Service",
    category: "maps",
    subTitle: "Custom Vector Tile Hosting",
    link: "https://docs.mapbox.com/mapbox-tiling-service/guides/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    title: "Style Specification",
    category: "maps",
    subTitle: "GL Vector Styling Syntax",
    link: "https://docs.mapbox.com/mapbox-gl-js/style-spec/",
    iconClass: "fa-regular fa-file",
  },
  {
    type: "tile",
    title: "Vector Tiles API",
    category: "maps",
    subTitle: "Vector Data in small chunks",
    link: "https://docs.mapbox.com/api/maps/vector-tiles/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    title: "Raster Tiles API",
    category: "maps",
    subTitle: "Raster Images for web maps",
    link: "https://docs.mapbox.com/api/maps/raster-tiles/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "maps",
    title: "Static Images API",
    subTitle: "Generate Customized Maps as Images",
    link: "https://docs.mapbox.com/api/maps/static-images/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "maps",
    title: "Static Tiles API",
    subTitle: "Serve raster tiles from Studio styles",
    link: "https://docs.mapbox.com/api/maps/static-tiles/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "maps",
    title: "Styles API",
    subTitle: "Get/set map styles, fonts, and images",
    link: "https://docs.mapbox.com/api/maps/styles/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "maps",
    title: "TileQuery API",
    subTitle: "Retrieve feature data from vector tilesets",
    link: "https://docs.mapbox.com/api/maps/tilequery/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "maps",
    title: "Uploads API",
    subTitle: "Transform geographic data into tilesets",
    link: "https://docs.mapbox.com/api/maps/uploads/",
    iconClass: "fa-solid fa-gear",
  },

  {
    type: "tile",
    category: "maps",
    title: "Datasets API",
    subTitle: "Get/Set features in datasets",
    link: "https://docs.mapbox.com/api/maps/datasets/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "maps",
    title: "Fonts API",
    subTitle: "Manage fonts used in mapbox styles",
    link: "https://docs.mapbox.com/api/maps/fonts/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "maps",
    title: "Maps SDK for iOS",
    subTitle: "Build amazing interactive maps on iOS",
    link: "https://docs.mapbox.com/ios/",
    iconClass: "fa-brands fa-apple",
  },
  {
    type: "tile",
    category: "maps",
    title: "Maps SDK for Android",
    subTitle: "Build amazing interactive maps on Android",
    link: "https://docs.mapbox.com/android/",
    iconClass: "fa-brands fa-android",
  },
  {
    type: "tile",
    category: "maps",
    title: "Static Images Playground",
    subTitle: "Generate Customized Maps as Images",
    link: "https://docs.mapbox.com/playground/static/",
    iconClass: "fa-regular fa-hand-pointer",
  },
  {
    type: "tile",
    category: "maps",
    title: "Tilequery Playground",
    subTitle: "Retrieve feature data from vector tilesets",
    link: "https://docs.mapbox.com/playground/tilequery/",
    iconClass: "fa-regular fa-hand-pointer",
  },
  // //
  // // NAVIGATION
  // //
  {
    type: "category",
    title: "Navigation",
    category: "navigation",
    subTitle: "Add turn-by-turn navigation, create optimized routes, and more.",
  },

  {
    type: "tile",
    category: "navigation",
    title: "Navigation SDK for iOS",
    subTitle: "Build navigation into apps on iOS",
    link: "https://docs.mapbox.com/ios/navigation/",
    iconClass: "fa-brands fa-apple",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Navigation SDK for Android",
    subTitle: "Build navigation into apps on Android",
    link: "https://docs.mapbox.com/android/navigation/",
    iconClass: "fa-brands fa-android",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Directions API",
    subTitle: "get directions",
    link: "https://docs.mapbox.com/api/navigation/directions/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Map Matching API",
    subTitle: "Snap fuzzy data to roads",
    link: "https://docs.mapbox.com/api/navigation/map-matching/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Isochrone API",
    subTitle: "Calculate Travel Time Areas",
    link: "",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Optimization API",
    subTitle: "Get a duration-optimized route between several locations",
    link: "https://docs.mapbox.com/api/navigation/isochrone/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Optimization API",
    subTitle: "optimized routing for logistics fleets",
    link: "https://docs.mapbox.com/api/navigation/optimization/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Matrix API",
    subTitle: "get travel times between many points.",
    link: "https://docs.mapbox.com/api/navigation/matrix/",
    iconClass: "fa-solid fa-gear",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Directions API Playground",
    subTitle: "try out the directions API.",
    link: "https://docs.mapbox.com/playground/directions/ ",
    iconClass: "fa-regular fa-hand-pointer",
  },
  {
    type: "tile",
    category: "navigation",
    title: "Isochrone API Playground",
    subTitle: "Calculate Travel Time Areas.",
    link: "https://docs.mapbox.com/api/navigation/matrix/",
    iconClass: "fa-regular fa-hand-pointer",
  },
  // //
  // // SEARCH
  // //
  {
    type: "category",
    title: "Search",
    category: "search",
    subTitle: "Turn coordinates into addresses or addresses into coordinates.",
  },

  {
    type: "tile",
    category: "search",
    title: "Search SDK for iOS",
    subTitle: "build address search into iOS apps.",
    link: "https://docs.mapbox.com/ios/search/overview/",
    iconClass: "fa-brands fa-apple",
  },
  {
    type: "tile",
    category: "search",
    title: "Search SDK for Android",
    subTitle: "build address search into Android apps.",
    link: "https://docs.mapbox.com/android/search/overview/",
    iconClass: "fa-brands fa-android",
  },
  {
    type: "tile",
    category: "search",
    title: "Mapbox Search JS",
    subTitle: "build address search into web apps",
    link: "https://docs.mapbox.com/mapbox-search-js/",
    iconClass: "fa-brands fa-square-js",
  },
  {
    type: "tile",
    category: "search",
    title: "Geocoding API",
    subTitle: "Turn addresses into coordinates and vice versa",
    link: "https://docs.mapbox.com/api/search/geocoding/",
  },
  {
    type: "tile",
    category: "search",
    title: "Japan Search API",
    subTitle: "Search for addresses in Japan",
    link: "https://docs.mapbox.com/api/search/search/",
  },
  {
    type: "tile",
    category: "search",
    title: "Mapbox GL Geocoder",
    subTitle: "A geocoder control for Mapbox GL JS",
    link: "https://github.com/mapbox/mapbox-gl-geocoder",
    iconClass: "fa-brands fa-square-js",
  },

  {
    type: "tile",
    category: "search",
    title: "Address Autofill",
    subTitle: "autofill postal addresses",
    link: "https://docs.mapbox.com/mapbox-search-js/guides/autofill/",
    iconClass: "fa-brands fa-square-js",
  },
  {
    type: "tile",
    category: "search",
    title: "Geocoding Playground",
    subTitle: "Try out the geocoing API",
    link: "https://docs.mapbox.com/search-playground/",
  },
  // //
  // // VISION
  // //
  {
    type: "category",
    title: "Vision",
    category: "vision",
    subTitle: "Interpret road scenes in real-time",
  },
  {
    type: "tile",
    category: "vision",
    title: "Vision SDK for iOS",
    subTitle: "Interpet road scenes using device camera",
    link: "https://docs.mapbox.com/ios/vision/",
    iconClass: "fa-brands fa-apple",
  },
  {
    type: "tile",
    category: "vision",
    title: "Vision SDK for Android",
    subTitle: "Interpet road scenes using device camera",
    link: "https://docs.mapbox.com/android/vision/",
    iconClass: "fa-brands fa-android",
  },
  {
    type: "tile",
    category: "vision",
    title: "Traffic Signs",
    subTitle: "Traffic Sign Image Reference",
    link: "https://docs.mapbox.com/traffic-signs/overview/",
    iconClass: "fa-regular fa-file",
  },
  // //
  // // DATA
  // //
  {
    type: "category",
    title: "Data",
    category: "data",
    subTitle:
      "Add location datasets to any map, platform, or intelligence solution.",
  },
  {
    type: "tile",
    category: "data",
    title: "Tilesets",
    subTitle: "Ready to use vector, raster, and elevation data",
    link: "",
    iconClass: 'fa-solid fa-database"',
  },
  {
    type: "tile",
    category: "data",
    title: "Mapbox Boundaries",
    subTitle: "Global boundary polygons",
    link: "https://docs.mapbox.com/data/boundaries/",
    iconClass: 'fa-solid fa-database"',
  },
  {
    type: "tile",
    category: "data",
    title: "Mapbox Movement",
    subTitle: "Understand where and when people are moving",
    link: "https://docs.mapbox.com/data/movement/",
    iconClass: 'fa-solid fa-database"',
  },
  {
    type: "tile",
    category: "data",
    title: "Traffic Data",
    subTitle: "Global Vehicle Traffic",
    link: "https://docs.mapbox.com/data/traffic/",
    iconClass: 'fa-solid fa-database"',
  },
];
